# ==================================================================
# Based on Ubuntu
# ------------------------------------------------------------------
#  C / C++ / Python2 / Python3 / PHP / Golang / NodeJS
# ==================================================================

ARG BUILD_SRC=/root/build
FROM docker.io/ubuntu:rolling
LABEL maintainer="xczh <xczh.me@foxmail.com>"
USER root
WORKDIR /root
SHELL ["/bin/bash", "-c"]

# ==================================================================
# add files
# ------------------------------------------------------------------

COPY build/ $BUILD_SRC/

# ==================================================================
# prepare
# ------------------------------------------------------------------

RUN echo "build_src: $BUILD_SRC" && \
    ls /root/build/ && \
    mv -f $BUILD_SRC/ide-run /usr/sbin/ && \
    mv -f $BUILD_SRC/ide-bin/ /usr/local/ && \
    ls -lah /usr/local/ide-bin/ && \
    chmod -R a+x /usr/sbin/ide-run /usr/local/ide-bin/* && \
    rm -rf $BUILD_SRC

CMD ["/bin/bash"]
