# ==================================================================
# Based on Ubuntu
# ------------------------------------------------------------------
#  C / C++ / Python2 / Python3 / PHP / Golang / NodeJS
# ==================================================================

FROM docker.io/ubuntu:rolling
LABEL maintainer="xczh <xczh.me@foxmail.com>"
USER root
WORKDIR /root
SHELL ["/bin/bash", "-c"]

# ==================================================================
# add files
# ------------------------------------------------------------------

COPY build/ /tmp/build/

# ==================================================================
# prepare
# ------------------------------------------------------------------

RUN ls -lah /tmp/build/ && \
    mv -f /tmp/build/ide-run /usr/sbin/ && \
    mv -f /tmp/build/ide-bin/ /usr/local/ && \
    ls -lah /usr/local/ide-bin/ && \
    chmod -R a+x /usr/sbin/ide-run /usr/local/ide-bin/* && \
    rm -rf /tmp/build

CMD ["/bin/bash"]
