# ------------------------------------------------------------------------------
# Pull Base Image
# From Ubuntu LTS
FROM docker.io/ubuntu:latest
MAINTAINER xczh <xczh.me@foxmail.com>

# ------------------------------------------------------------------------------
# Install Base
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates && \
    sed -i 's|http://archive.ubuntu.com|https://mirrors.tuna.tsinghua.edu.cn|' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y nano vim htop net-tools curl wget git tzdata inetutils-ping openssh-server openssl && \
    mkdir /var/run/sshd && \
    echo "Asia/Shanghai" > /etc/timezone && \
    echo 'export LANG="C.UTF-8"' >> /etc/profile && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# ------------------------------------------------------------------------------
# Install Python2 and Python3
RUN apt-get install -y python python3 && \
    mkdir -p ~/.pip && \
    echo "[global]" >> ~/.pip/pip.conf && \
    echo "index-url = https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/" >> ~/.pip/pip.conf && \
    curl -L  https://bootstrap.pypa.io/get-pip.py | python2 && \
    curl -L  https://bootstrap.pypa.io/get-pip.py | python3

# -------------------------------------------------------------------------------
# Install Supervisor
RUN apt-get install -y supervisor && \
    sed -i 's/^\(\[supervisord\]\)$/\1\nnodaemon=true/' /etc/supervisor/supervisord.conf

# ------------------------------------------------------------------------------
# Install PHP
RUN apt-get install -y php-cli php-json php-mysql php-mcrypt php-soap php-mbstring php-gd php-curl && \
    curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

# ------------------------------------------------------------------------------
# Install Golang 
# config GOROOT, GOPATH, PATH in ide-run
ARG GOLANG_VER=1.9.2
RUN curl -o /tmp/go${GOLANG_VER}.linux-amd64.tar.gz https://storage.googleapis.com/golang/go${GOLANG_VER}.linux-amd64.tar.gz && \
    tar -zxvf /tmp/go${GOLANG_VER}.linux-amd64.tar.gz -C /usr/local/ && \
    ln -s /usr/local/go/bin/go /usr/local/bin/go && \
    ln -s /usr/local/go/bin/gofmt /usr/local/bin/gofmt && \
    ln -s /usr/local/go/bin/godoc /usr/local/bin/godoc && \
    rm -f /tmp/go${GOLANG_VER}.linux-amd64.tar.gz

# ------------------------------------------------------------------------------
# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    apt-get install -y nodejs && \
    ln -s /usr/bin/nodejs /usr/local/bin/node && \
    npm config set registry https://registry.npm.taobao.org && \
    npm install -g http-server

# ------------------------------------------------------------------------------
# Install Cloud9
RUN git clone --single-branch --depth 1 https://github.com/c9/core.git /cloud9 && \
    apt-get install -y gcc g++ make && \
    /cloud9/scripts/install-sdk.sh && \
    sed -i -e 's_127.0.0.1_0.0.0.0_g' /cloud9/configs/standalone.js

# ------------------------------------------------------------------------------
# Add Volumes
VOLUME /workspace

# ------------------------------------------------------------------------------
# Clean up
RUN apt-get clean -y && \
    apt-get autoremove -y && \
    apt-get autoclean -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.cache && \
    npm cache clean

# ------------------------------------------------------------------------------
# Expose HTTP Port
EXPOSE 80

# ENV
ENV C9_AUTH webide:webide

# ide-init scripts
ADD build/user.settings /root/.c9/user.settings
ADD build/ide-run /usr/sbin/
ADD ide-bin/ /usr/local/

# supervisor config
ADD conf/supervisord.conf /etc/supervisor/supervisord.conf

# start supervisor
CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
